debian/tmp/usr/bin/guild
debian/tmp/usr/bin/guile-config
debian/tmp/usr/bin/guile-snarf
debian/tmp/usr/bin/guile-tools
debian/tmp/usr/include/*
debian/tmp/usr/lib/*/*.a
debian/tmp/usr/lib/*/libguile-@DEB_SRC_EFF_VER@.so
debian/tmp/usr/lib/*/pkgconfig/guile-@DEB_SRC_EFF_VER@.pc
debian/tmp/usr/share/aclocal/guile.m4
debian/tmp/usr/share/guile/*/scripts/*
examples usr/share/doc/guile-@DEB_SRC_EFF_VER@-dev
